### ISSUE TITLE
Options - maturity / expiration date issue

### ISSUE THREAD

**Issue by tristanpc** [OpenFIGI/api-examples#21]
I work in ETDs and I'm trying to pass an expiration date (or maturity date) using an adaption of the C# example project. I've added strike and optionType attributes successfully but I can't seem to get either a maturityDate or expirationDate working. Anyone have working JSON for this? I get an HTTP500 from OpenFigi, with no detail on the error server side.

This JSON fails:
{"idType":"ID_EXCH_SYMBOL","idValue":"SNAP","exchCode":"US","optionType":"Put","securityType":"Equity Option","securityType2":"Option","expiration":["2018-01-19","2018-01-19"],"strike":[12.0,12.5]}]

(as does the similar version with expirationDate)
...but this JSON, without a maturityDate or expirationDate filter succeeds. 

{"idType":"TICKER","idValue":"SNAP 01/19/18 P12.5","exchCode":"US","marketSecDes":"Equity","optionType":"Put","securityType":"Equity Option"},{"idType":"ID_EXCH_SYMBOL","idValue":"SNAP","exchCode":"US","optionType":"Put","securityType2":"Option","strike":[12.0,12.0]}

Without a working maturityDate filter, the code brings back many results instead of one and OpenFigi doesn't appear to supply a maturityDate alone in part of the response, so we would be reduced to stripping it from the ticker, which isn't straightforward as the date format varies there.

Any working JSON for options (or even futures) with a working maturityDate or expirationDate attribute please?
Thanks in advance.

**Comment by jayflo** [comment]
Thanks for reporting this issue and the examples. 
 My initial thought is that it might have to do with the start and end dates being the same (but that is valid and should be fixed).

I'll look into this Monday.

**Comment by jayflo** [comment]
@tristanpc I believe I found the problem and deployed a fix.  Please test and let me know if you see any more issues.  If you retry a recently failed request, please adjust the request to be unique since the cache my still need to be cleared of the previous result.

**Comment by tristanpc** [comment]
Great, that's options working, thank you! I still have a problem with futures, though I've only tried one so far. With options I'm using expirationDate successfully:
e.g. {"idType":"ID_EXCH_SYMBOL","idValue":"SNAP","exchCode":"US","optionType":"Put","securityType2":"Option","expiration":["2018-01-19","2018-01-19"],"strike":[12.0,12.5]}

...and a future without a maturityDate filter also works:
{"idType":"ID_EXCH_SYMBOL","idValue":"FMAS","exchCode":"EUX","securityType2":"Future"}

...but adding a maturity filter retrieves a "no identifier found" message (no http error, however). 
{"idType":"ID_EXCH_SYMBOL","idValue":"FMAS","exchCode":"EUX","securityType2":"Future","maturity":["2018-12-19","2018-12-31"]}
Now, I wondered if maturityDate were the not the intended date property for futures but I don't see a better-named alternative so I think maturityDate must be the right one.
Note, in this example the last traded date is actually December 21st, 2018 and you do see that December contract come back when you search without a maturity date (albeit you don't see the 21st in any of the response fields).

Perhaps not a bug now but do I need some education on how to submit the maturity date for monthly-traded futures (the most common kind)?

Thanks for your fantastic help in fixing options so quickly.

**Comment by jayflo** [comment]
@tristanpc we're still working on futures.  When it's ready I believe that expiration will be the key you'll use to filter futures.  

The API documentation and the openapi schema will be updated once it's out.  I'll leave this open and try to remember to post back here as well.

**Comment by tristanpc** [comment]
Ok, no problem. As I see it, futures are working well enough for me to test thoroughly. With no strike prices to worry about, they're aren't that many contracts, so I can download all prompts and just delete the ones with delivery dates in the past. Any information on what still needs to be done for Futures would be very welcome and again thanks for your rapid responses. I'm going to enjoy coding against this API.
